### PR TITLE
sneaky question

### PR DESCRIPTION
**Pull request by jdart**
Hi Derek, Where can i find `wrist-rest-right.stl` ?

### CODE REVIEW

**Comment by drorchen** [comment]
I was about to ask exactly the same question.

**Comment by YvesH87** [comment]
same here. Just use the File from the link. Seems to work fine. My first Download was corrupted.

https://github.com/dereknheiley/ibnuda.dactyl-keyboard/tree/dkn/things

**Comment by uqs** [comment]
The README explains how to run the clojure code and OpenSCAD to produce all the STL files.

**Comment by jdart** [comment]
The clojure imports the model here https://github.com/dereknheiley/dactyl-manuform-tight/blob/master/src/dactyl_keyboard/dactyl.clj#L892 but I don't see it referenced anywhere else.

**Comment by YvesH87** [comment]
> The README explains how to run the clojure code and OpenSCAD to produce all the STL files.

It just makes the SCAD but in the SCAD it imports an STL wich is not in there. But as i edited my Post it works fine with the other File.

**Comment by uqs** [comment]
Oh, I'm sorry you're right. Unlike other Dactyl forks it doesn't generate that model from scratch but assumes some STL file present, which it then only punches holes into. Maybe there were other manual touch ups to that file?

From the renderings, the wrist rests look like the ones from https://github.com/crystalhand/dactyl-keyboard, you might need to patch the code a little to compile, though. For that, have a look at the top commit here: https://github.com/uqs/dactyl-keyboard

**Comment by dereknheiley** [comment]
Sorry about that guys, i only recently realized it was missing. The latest code now does actually generate the wrist rest (i used crystalhands code as a starting point) so you can play around with the angles. Also the original STL version of the wrist rest is added now in case you wanted it for reference.

**Pull request closed without merging**
